// This file was generated by Prisma and assumes you have installed the following:
import { defineConfig, env } from "prisma/config";
import "dotenv/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations"
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL || env("DATABASE_URL")
  }
});

/**
** Add the following scripts to your package.json:

"db:push": "prisma db push",
"db:studio": "prisma studio"
 */
